server:
  port: 10086
spring:
  application:
    name: hz-registry
eureka:
  client:
    fetch-registry: true #拉取注册中心服务列表信息       false的话不显示
    register-with-eureka: true #拉取eureka, false的话不显示
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
  server:
    enable-self-preservation: false # 关闭自我保护
    eviction-interval-timer-in-ms: 5000 # 每隔5秒进行一次服务列表清理
