server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
#  该配置可以防止别的服务请求拿到的是机器名而不是ip
#  instance:
#    ip-address: 127.0.0.1 #把ip定义死
#    prefer-ip-address: true #定义ip
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
fdfs:
  so-timeout: 2500
  connect-timeout: 600
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 192.168.1.120:22122
hz:
  upload:
    baseUrl: http://image.huizhong.com/ #也可写 "http://image.huizhong.com/"
    allowTypes:
      - image/png
      - image/jpeg
      - image/jpg
      - image/bmp